### ISSUE TITLE
feature request: copy installation messages

### ISSUE THREAD

**Issue by edmundlaugasson** [bkw777/mainline#105]
Currently not possible to copy installation messages from terminal window. After marking text, either SHIFT+CTRL+C or mouse right button does not allow to copy marked text. Thank you for considering this!

**Comment by bkw777** [comment]
I don't know why it behaves this way, but it does work, just oddly. I'll look into making it work more normally, but until then try this:
Highlight the text, just ordinary left-mouse-button.
Then in a text editor just press the middle mouse button.

Not right-click paste, just press the middle button (or virtual middle button by pressing both buttons or however your desktop provides virtual middle button if you don't have actual middle button)

**Comment by edmundlaugasson** [comment]
I guess I tried to press mouse wheel (I'm aware  of that), but didn't work. However have to test it at some point.
