### ISSUE TITLE
unsolved dependency with mainline 1.0.15 in Ubuntu 20.04 LTS (Linux Mint 20)

### ISSUE THREAD

**Issue by edmundlaugasson** [bkw777/mainline#107]
unsolved dependency: libgdk-pixbuf-2.0-0 (>=2.22.0)
[availability in Ubuntu](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libgdk-pixbuf-2.0-0&searchon=names)

It is weird, that installed is v2.40.0, but required is >=2.22.0
```
dpkg -l | grep libgdk-pixbuf
ii  libgdk-pixbuf2.0-0:amd64                     2.40.0+dfsg-3ubuntu0.2                amd64        GDK Pixbuf library
ii  libgdk-pixbuf2.0-bin                         2.40.0+dfsg-3ubuntu0.2                amd64        GDK Pixbuf library (thumbnailer)
ii  libgdk-pixbuf2.0-common                      2.40.0+dfsg-3ubuntu0.2                all          GDK Pixbuf library - data files
```

**Comment by bkw777** [comment]
Is this still a problem? It looks like some kind of dpkg or apt db problem. You're right that it sure looks like you have the dependecy satisfied, but I don't know what I can do about it. The deb says what the requirement is, and dpkg resolves that pass/fail on the installing system not me on the building system. All I can do is change what requirement gets put into the deb, not what dpkg does with it. And the number in the deb is already lower than what you have installed, so, there's nothing else to do.

I supposed it could be something like, you tried to install a 32bit version of the app but only have 64bit versions of the libraries? That might possibly be one way you could get a seemingly nonsense error like that? I don't really think that happened I'm just trying to think of any possible way to get that message short of "corrupt apt db".

**Comment by edmundlaugasson** [comment]
I've moved with my main production machines away from Linux Mint to another distro (Arch Linux based). It is easy to test - just take latest Linux Mint ISO file and run it in virtual machine, e.g. VirtualBox or similar and try to install mainline app and latest kernel(s). Then you can see, whether it is still an issue. Applying software updates would be also useful beforehand.
One laptop I had with Linux Mint, helping my friend, there I installed separate repository in order to get latest kernel and not mainline app:
- 5.14.x - [https://launchpad.net/%7Etuxinvader/+archive/ubuntu/lts-mainline](https://launchpad.net/~tuxinvader/+archive/ubuntu/lts-mainline)
- 5.10.x - [https://launchpad.net/%7Etuxinvader/+archive/ubuntu/lts-mainline-longterm](https://launchpad.net/~tuxinvader/+archive/ubuntu/lts-mainline-longterm) (LTS)
These repos also mentioned here #106 as there was also another dependency issue, which you marked unable to solve.

**Comment by basmevissen** [comment]
> Is this still a problem?
Yes, it still is. The package does not install on Ubuntu 20.04 or Linux Mint Uma. Can you please take a look?

**Comment by bkw777** [comment]
The .deb I provide in releases is just for reference and minimal convenience. It's always built on whatever is the latest version of ubuntu at the time, so it's expected that it may not install on older versions.

For a wider range of supported target systems, use Cappelikan's PPA linked in the main readme or build from source.

I should specify the target/supported ubuntu version for that .deb in the discription in releases. Sorry for not doing that.
