### ISSUE TITLE
check directory kernel status invalid or no

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#114]
I saw such a bug, when something happened while processing the kernel list in the mainline directory writes the zero file invalid, then when the kernel is read the status does not change until I manually delete the zero file invalid

**Comment by bkw777** [comment]
agreed, it should re-scan

**Comment by bkw777** [comment]
Fixed by f78d352

Now we scrape timestamps from both the main index and the cached per-kernel indexes, and compare them to detect out of date cached indexes and update them.
