### ISSUE TITLE
I offer a script for automatic replacement of the libc6 version from 2.33 - 34 to 2.27

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#116]
mkdir !
sudo dpkg-deb -R linux-header*-generic*_amd64.deb !
cd !/DEBIAN
sudo sed -i 's/libc6 (>=[^)]*/libc6 (>= 2.27/' control 
cd ../..
sudo dpkg-deb -b ! linux-header*_amd64.deb
sudo rm -rf !

I think that when all kernel files will be downloaded in the directory where the kernel lies we run this script and we correct the libc6 version in the control file

As far as I understand, after downloading the kernel files and entering the root password, you need to insert the code of this script into the startup sequence to save the debian / control file P.S. Brian think do I think this is the way out?

**Comment by cappelikan** [comment]
> With deb packages, the situation is extremely incomprehensible and complicated, it seems the authors gave up on the situation with libc6 and are only raising its version, so my method just solves this issue, if the ator doesn't care that I have 20.04 lts or 18.04 lts, ​​then what else is left for me to do b except how to correct the version in DEBIAN / contol? nothing, and in addition, I do not assign the rights to the kernel, I locally solve the dependence on the obviously overstated version in the direction of lowering it

**Comment by cappelikan** [comment]
I forcibly install the libc6 version to version 2.27, thereby starting from the libc6 version recommended in Bionic 18.04, that is, I am targeting from ubuntu 18.04 and higher

**Comment by bkw777** [comment]
This is wrong.
