### ISSUE TITLE
E: Internet connection is not active

### ISSUE THREAD

**Issue by cchicote** [bkw777/mainline#123]
Hi,

I was using mainline to update kernel on the cluster that i'm managing but it seems that one of the servers cannot run `mainline --list`:

```
➜  ~ sudo mainline --list
mainline 1.0.15
Distribution: Ubuntu 20.04.1 LTS
Architecture: amd64
Running kernel: 5.8.0-29-lowlatency
E: Internet connection is not active
E: Internet connection is not active
Fetching index from kernel.ubuntu.com...
E: ERR
----------------------------------------------------------------------
Found installed: 5.4.0.54.57
Found installed: 5.8.0-29.31~20.04.1
Found installed: 5.4.0-54.60
----------------------------------------------------------------------
----------------------------------------------------------------------

======================================================================
Available Kernels
======================================================================
5.8.0.29.31                      Installed
5.4.0.54.60                      Installed
5.4.0.54.57                      Installed
➜  ~
```

Mainline worked perfectly with the 4 other servers that i used it on, and there is no noticeable difference between the current server and the others.
I can ping `kernel.ubuntu.com` and it's not taking an abnormally long time.

Thanks a lot for your help

**Comment by bkw777** [comment]
It uses aria2c to download.
Run with --debug, and/or, use aria2c manually to try to download any of the index.html's from kernel.ubuntu.com
Try something like
```aria2c -l a2c.log -o a2c.html https://kernel.ubuntu.com/~kernel-ppa/mainline/```
And see what's in a2c.log and a2c.html for clues.
Do the same thing from a working machine and look for differences.

**Comment by bkw777** [comment]
no response
