### ISSUE TITLE
Mainline --install install kernel version but does not make it the running kernel

### ISSUE THREAD

**Issue by nodje** [bkw777/mainline#125]
First time usage, everything works as expected, but after a `mainline -install 5.4.0` and a reboot the old version is still the one active.

```
mainline 1.0.15
Distribution: Ubuntu 21.10
Architecture: amd64
Running kernel: 5.13.0-22-generic
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.4.0-050400.201911242031
Found installed: 5.13.0.22.33
Found installed: 5.13.0-21.21
Found installed: 5.13.0-22.22
----------------------------------------------------------------------
----------------------------------------------------------------------
Latest update: 5.15.6
Latest point update: 5.13.19
----------------------------------------------------------------------
```

I'm not sure this is expected.

From the documentation I gather this should simply work and make 5.4.0  the active kernel.

**Comment by Grant12311** [comment]
I'm not very knowledgeable about this stuff, but I think your system will always boot the newest installed kernel unless configured not to.

**Comment by nodje** [comment]
You're probably right, at least that's how my system behaves.
Installing latest kernel makes it the default, while installing an older one just lists it as installed but do not activate it.
All installed kernels are available in grub.cfg so that's probably the way to activate an older kernel.

On a server it's not so obvious as you never get to see the grub menu.
I expected `mainline` to have a way to make this transparent and avoid to have to fiddle with grub.cfg.
