### ISSUE TITLE
error /usr/bin/env: option -- 'C' invalid

### ISSUE THREAD

**Issue by MarceloMachadoxD** [bkw777/mainline#128]
machado@machado-AO751h:~$ uname -a
Linux machado-AO751h 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:35 UTC 2020 i686 i686 i686 GNU/Linux
machado@machado-AO751h:~$ 

machado@machado-AO751h:~$ sudo mainline --install-latest
[sudo] senha para machado: 
mainline 1.0.15
Distribution: Ubuntu 16.04.6 LTS
Architecture: i386
Running kernel: 4.4.0-186-generic
Fetching index from kernel.ubuntu.com...

(process:2772): GLib-GIO-CRITICAL **: g_output_stream_close: assertion 'G_IS_OUTPUT_STREAM (stream)' failed

(process:2772): GLib-GIO-CRITICAL **: g_output_stream_clear_pending: assertion 'G_IS_OUTPUT_STREAM (stream)' failed
OK
----------------------------------------------------------------------
Found installed: 3.13.0-170.220
Found installed: 4.4.0-179.209
Found installed: 4.4.0-186.216
Found installed: 3.13.0-117.164
Found installed: 4.4.0.186.192
Found installed: 3.13.0.170.181
Found installed: 3.13.0-32.57
----------------------------------------------------------------------
----------------------------------------------------------------------
Latest update: 5.10.5

Install Kernel Version 5.10.5 ? (y/n): y
Preparing to install '5.10.5'
kinst() flist += i386/linux-image-5.10.5-051005-generic_5.10.5-051005.202101061537_i386.deb
kinst() flist += i386/linux-headers-5.10.5-051005-generic_5.10.5-051005.202101061537_i386.deb
kinst() flist += amd64/linux-headers-5.10.5-051005_5.10.5-051005.202101061537_all.deb
kinst() flist += i386/linux-modules-5.10.5-051005-generic_5.10.5-051005.202101061537_i386.deb
/usr/bin/env: opção -- 'C' inválida
Try '/usr/bin/env --help' for more information.
E: Installation completed with errors
machado@machado-AO751h:~$

**Comment by marcelog09** [comment]
Same here
