### ISSUE TITLE
Mainline not show new version of kernel from kernel-ppa

### ISSUE THREAD

**Issue by VladimirMrzv** [bkw777/mainline#136]
Mainline not show new version of kernel from kernel-ppa

![image](https://user-images.githubusercontent.com/81020401/165989489-62b224c9-4538-4d01-9c32-5ae998c7c08b.png)

**Comment by bkw777** [comment]
we don't include failed builds

**Comment by VladimirMrzv** [comment]
5.17.5 failed build too?
How you check?
