### ISSUE TITLE
kernel 5.18.1 not showing up?

### ISSUE THREAD

**Issue by mikehardy** [bkw777/mainline#138]
Not sure if it's me or if others see this?

I verify that the kernel exists https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.18.1/

I know there is no clean cache button - #45 - so I did `mainline --clean-cache` then `mainline --list` and it does not show up? It only shows me 5.18.0

Not the biggest problem in the world of course, just curious if others see this, and if so any ideas to troubleshoot

Thanks, as ever, for mainline

**Comment by bkw777** [comment]
Look at the link you posted.
"
Test amd64/build failed (rc=2, on=amd64, time=0:08:45, log=[amd64/log](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.18.1/amd64/log))

Test amd64/self-tests failed (rc=2, on=amd64, time=0:00:44, log=[amd64/self-tests/log](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.18.1/amd64/self-tests/log))
"

**Comment by mikehardy** [comment]
I need a facepalm reaction emoji. Sorry for the noise

**Comment by bkw777** [comment]
I said that terseley and I aplogize for that. No problem of course! I wouldn't want to discourage bug reporting.
In this case, in fact it's been a low level todo forever to scan that output and indicate it right in the app to avoid exactly that mystery. It's bad ux as it is right now.
