### ISSUE TITLE
5.18. not working with virtual box

### ISSUE THREAD

**Issue by PaulRehel** [bkw777/mainline#140]
Oracle Virtualbox 6.1.34 works with 5.17.13 but not 5.18.0 or 5.18.2.
Building the main VirtualBox module.
Building the net filter module.
Error building the module:
make V=1 CONFIG_MODULE_SIG= CONFIG_MODULE_SIG_ALL= -C /lib/modules/5.18.2-051802-generic/build M=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 -j8 modules
make[1]: warning: -j8 forced in submake: resetting jobserver mode.
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-3ubuntu1) 11.3.0
  You are using:           gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
------------------------------
22.04 (updated)
Nvidia driver:515.48.07 (latest)

**Comment by bkw777** [comment]
kernel compatibility is not our problem. This app just downloads and installs .deb packages and that's it. There are all kinds of text on the mainline-ppa web site and ubuntu wiki about how the mainline kernels are different and full of things that may break compatibility at any time.
