### ISSUE TITLE
failed to build launchpad ubuntu 22.04 and ubuntu 22.10 packages 

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#142]
valac -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.0.15"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' -X -D'URI_KERNEL_UBUNTU_MAINLINE="https://kernel.ubuntu.com/~kernel-ppa/mainline/"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 \
	src/Common/*.vala src/Utility/*.vala src/Console/*.vala -o mainline
src/Common/LinuxKernel.vala:196.4-196.22: warning: `GLib.Thread.create' has been deprecated since 2.32. Use new Thread<T> ()
  196 | 			Thread.create<void> (query_thread, true);
      | 			^~~~~~~~~~~~~~~~~~~                      
src/Utility/TeeJee.FileSystem.vala:205.17-205.41: warning: `GLib.DateTime.from_timeval_utc' has been deprecated since 2.62
  205 | 				return (new DateTime.from_timeval_utc(info.get_modification_time())).to_local();
      | 				            ^~~~~~~~~~~~~~~~~~~~~~~~~                                           
src/Utility/TeeJee.FileSystem.vala:205.43-205.68: warning: `GLib.FileInfo.get_modification_time' has been deprecated since 2.62
  205 | 				return (new DateTime.from_timeval_utc(info.get_modification_time())).to_local();
      | 				                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~                
src/Utility/AsyncTask.vala:138.5-138.23: warning: `GLib.Thread.create' has been deprecated since 2.32. Use new Thread<T> ()
  138 | 				Thread.create<void> (read_stdout, true);
      | 				^~~~~~~~~~~~~~~~~~~                     
src/Utility/AsyncTask.vala:146.5-146.23: warning: `GLib.Thread.create' has been deprecated since 2.32. Use new Thread<T> ()
  146 | 				Thread.create<void> (read_stderr, true);
      | 				^~~~~~~~~~~~~~~~~~~                     
src/Common/Main.vala:43.34-43.65: error: value is less accessible than constant `LOCALE_DIR'
   43 | public const string LOCALE_DIR = INSTALL_PREFIX + "/share/locale";
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
src/Common/Main.vala:44.35-44.79: error: value is less accessible than constant `APP_LIB_DIR'
   44 | public const string APP_LIB_DIR = INSTALL_PREFIX + "/lib/" + BRANDING_SHORTNAME;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Compilation failed: 2 error(s), 5 warning(s)
make[1]: *** [Makefile:70: mainline] Error 1

**Comment by bkw777** [comment]
See if 49fe94b2869233bf0c1dabaebba516fe260c8db0 fixes it.

**Comment by bkw777** [comment]
Looks like it built.

**Comment by cappelikan** [comment]
Yes everything turned out great
![Screenshot_20220715_022625](https://user-images.githubusercontent.com/7409626/179117920-da3ee9c4-d290-47cd-8dc6-197c41d9b97c.png)
