### ISSUE TITLE
Feature request: Verify libc version before attempting to install a new kernel

### ISSUE THREAD

**Issue by 64kramsystem** [bkw777/mainline#144]
New(er) kernels depend on new(er) libc versions; this implies that it's not possible to always a new kernel on a given Ubuntu version (which could ship an older version).

For example, the latest kernel, 5.19.x (but also some older ones) depends on libc 2.34; since Ubuntu 20.04 ships libc 2.31, it doesn't support this (packaged) kernel version.

Since this requirement it not displayed by the (mainline) installer, it's easy to end up with a broken apt configuration (due to packages being only partially installed).

It'd be therefore helpful for the user if mainline checked the libc version.

Checking the version is easy via standard unix tools (`dpkg -I $package.deb` includes the dependencies, and `dpkg --list libc6` will display the installed version(s).

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline/issues/87
