### ISSUE TITLE
get_username() reads file /etc/passwd to get user name.

### ISSUE THREAD

**Issue by kenjo** [bkw777/mainline#15]
its actually get_user_id_from_username() doing it 

This is not working on system using NIS  or LDAP or any other system that has the user information not in the /etc/passwd file. The user do not exist and the string in empty then mainline is trying to open/use the cache in / instead of in ~/ the home directory of the user.

you have to use the glibc function getpwuid() getpwnam() for this to work correctly on all linux systems.

**Comment by aljex** [comment]
Thanks I'll look into it. I'm away on vacation for a few more days so maybe not immediately.

**Comment by LucasChollet** [comment]
This can be closed as solved by d7943e56e7b73a2d96b862195f514e9c0dca0c5c.

**Comment by kenjo** [comment]
yes that commit looks like it fixes this issue.
