### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by gnarlin** [bkw777/mainline#16]
Downloading: 'linux-image-unsigned-5.3.7-050307-generic_5.3.7-050307.201910171955_amd64.deb'... 
ERROR                                                                 

Downloading: 'linux-modules-5.3.7-050307-generic_5.3.7-050307.201910171955_amd64.deb'... 
ERROR                                                                 

Downloading: 'linux-headers-5.3.7-050307_5.3.7-050307.201910171955_all.deb'... 
ERROR                                                                 

Downloading: 'linux-headers-5.3.7-050307-generic_5.3.7-050307.201910171955_amd64.deb'... 
ERROR

**Comment by gnarlin** [comment]
I'm running Ubuntu 19.10.

**Comment by bkw777** [comment]
I am seeing no problem downloading.

**Comment by gnarlin** [comment]
Well, I am. Is there any log or information that I can provide that can help figure out why I can't download those deb files?

**Comment by bkw777** [comment]
Install the latest version (1.0.3, the only deb in the releases tab for 1.0.3 is for 64bit 19.10 so you could use that if the ppa hasn't updated yet.)
Then run "mainline-gtk --debug"
and look for "aria2c" commands in the output. You may see something right in the debug output that explains it obviously without having to look further, or the next step would be copy one of the commands and try the same command manually, and further, maybe change some aria2c commandline options to make it more verbose.
