### ISSUE TITLE
5.19.10 is missing from kernel list

### ISSUE THREAD

**Issue by username227** [bkw777/mainline#161]
OK, so I have not seen a new kernel since 5.19.5 in the program. It would appear that 5.19.6 through 5.19.9 all failed to build, and that's why they weren't visible. (I'm using amd64).
But 5.19.10 was successful, but it still does not show up on the available kernels menu. I don't understand why that would be.
I was able to successfully install this kernel using the command line utility ubuntu-mainline-kernel.sh. Therefore, I'm wondering if this is some sort of bug.

**Comment by username227** [comment]
> PS .6/7/8/9 seem to have been successfully built in the last few hours
> 
> edit: it seems that because they weren't valid builds mainline marked them as invalid and one needs to run mainline --clean-cache or just delete the specific folders in /home/user/.cache/mainline/
This worked. Thanks!

**Comment by bkw777** [comment]
Wow, they retroactively rebuilt old failed builds? --clean-cache makes .6 .7 .8 .9 and .10 appear when they were already failed builds and no longer current. I didn't think they ever did that.

**Comment by sigaev-pro** [comment]
Hello! I have the same problem. Command `mainline --list` does not show new kernels 5.15+ versions.

```
mainline 1.0.16
Distribution: Ubuntu 22.04.1 LTS
Architecture: amd64
Running kernel: 5.15.0-52-generic
Fetching index from kernel.ubuntu.com...
OK

Fetching index...

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100 % 

----------------------------------------------------------------------
Found installed: 5.15.0-52.58
Found installed: 5.15.0.52.52
Found installed: 5.15.0-50.56
----------------------------------------------------------------------
----------------------------------------------------------------------

======================================================================
Available Kernels
======================================================================
6.0.6                            
6.0.5                            
6.0.4                            
6.0.3                            
6.0.1                            
6.0.0                            
5.15.0.52.58                     Installed
5.15.0.52.52                     Installed
5.15.0.50.56                     Installed
```

I'm using Ubuntu 22.04.

**Comment by bkw777** [comment]
> Hello! I have the same problem. Command `mainline --list` does not show new kernels 5.15+ versions.
> 
> ```
> mainline 1.0.16
> Distribution: Ubuntu 22.04.1 LTS
> Architecture: amd64
> Running kernel: 5.15.0-52-generic
> Fetching index from kernel.ubuntu.com...
> OK
> 
> Fetching index...
> 
> ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100 % 
> 
> ----------------------------------------------------------------------
> Found installed: 5.15.0-52.58
> Found installed: 5.15.0.52.52
> Found installed: 5.15.0-50.56
> ----------------------------------------------------------------------
> ----------------------------------------------------------------------
> 
> ======================================================================
> Available Kernels
> ======================================================================
> 6.0.6                            
> 6.0.5                            
> 6.0.4                            
> 6.0.3                            
> 6.0.1                            
> 6.0.0                            
> 5.15.0.52.58                     Installed
> 5.15.0.52.52                     Installed
> 5.15.0.50.56                     Installed
> ```
> 
> I'm using Ubuntu 22.04.

This is probably just "show previous N major versions = 0" default setting in settings. If you want to see 5.x kernels now that 6.x is out, then set show N previous majors to 1 or more, and then accept that startup will be slow and get slower and slower as it has to scan & refresh more and more kernels on every startup.

**Comment by smith558** [comment]
`mainline --clean-cache` fixed the issue for me

**Comment by keredson** [comment]
not showing 6.1 for me.  `--clean-cache` did nothing.

![image](https://user-images.githubusercontent.com/2049665/208483337-c9e4a0c7-35e7-4bf4-9405-7c384a766654.png)

```
derek@vivobook:~$ mainline --clean-cache
mainline 1.0.18
Distribution: Ubuntu 22.10
Architecture: amd64
Running kernel: 6.1.0-060100rc5-generic
Removed cached files in '/home/derek/.cache/mainline'
derek@vivobook:~$ mainline --list | head -n 30
mainline 1.0.18
Distribution: Ubuntu 22.10
Architecture: amd64
Running kernel: 6.1.0-060100rc5-generic
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.15.0-rc5+-383
Found installed: 5.19.5-1
Found installed: 5.19.0.26.23
Found installed: 6.1.0-060100rc5.202211132230
Found installed: 5.19.0-26.27
Found installed: 6.0.8-060008.202211101901
----------------------------------------------------------------------
----------------------------------------------------------------------

======================================================================
Available Kernels
======================================================================
6.1.0-rc5                        Running
6.1.0-rc4                        
6.1.0-rc3                        
6.1.0-rc1                        
6.0.9                            
6.0.8                            Installed
6.0.7                            
6.0.6                            
6.0.5                            
6.0.4                            
6.0.3                            
```

**Comment by karelfridrich** [comment]
> not showing 6.1 for me. `--clean-cache` did nothing.
> ....

Same here. The listing ends with 6.0.9. not even 6.0.11 - 14 shown.

**Comment by StatusCode404** [comment]
Yes I believe someone needs to contact the Ubuntu kernel team and ask them what's going on with 6.0.10--6.0.14 failing in their builds.

**Comment by bkw777** [comment]
They know, good grief.

**Comment by abdelouahabb** [comment]
6.1 is missing because there is a build issue
https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1.2/amd64/log
