### ISSUE TITLE
New kernels + sort TABs by version

### ISSUE THREAD

**Issue by Danik2343** [bkw777/mainline#163]
Add support for XanMod kernels and sort by version, for example, in 5 there will be versions of the fifth kernels and you can also make a tab in them for a specific branch.

**Comment by Danik2343** [comment]
I agree, it looks like Ukuu, but it will be much better this way, and will not be criticized because of this, the code for it is already closed.
P.S Some people think that the author of the original just threw people away, but there were 12 donations in 2 years, the project could have closed.

**Comment by VladimirMrzv** [comment]
Maybe add option to show only installed kernels, it would helps to find in big list for uninstalling

**Comment by bkw777** [comment]
xanmod appears to have a normal apt repo, which should be even more convenient than this app. This app really only exists because the ubuntu mainline ppa is not a normal ppa and can't be added to apt and used from aptitude, synaptic etc.
