### ISSUE TITLE
Linux-header install error

### ISSUE THREAD

**Issue by AviBen96** [bkw777/mainline#173]
Good monrning ! 

I am on Ubuntu 20.04 running official kernel 5.15. 

I am trying to to upgrade to any kernel above 5.16 because my wifi card is not recognized. 

Every install is successful (I can launch into the new kernel) but with errors of dependencies (libc3 et lib)  that cause the linux header not to be build properly. This results with problems for install my graphic card driver .... 

Any suggestion ?

**Comment by bkw777** [comment]
The help section of the readme got accidentally deleted. Just restored it.
See the libssl doc. Basically a known thing we can't do much about but work around it. It's a result of the way the mainline-ppa builds the kernel packages vs the dependency packages available in older targets. You're only option is to install some newer packages from newer targets, or don't use those newer kernels or upgrade your base system to the necessary version.
https://github.com/bkw777/mainline#help

**Comment by bkw777** [comment]
Can you give a more detailed description of the problem? It sounds like it exactly is a problem of meeting the dependencies, which means the suggestions in the help doc do actually address that. But it is a bit terse and maybe you didn't actually do what it says.
