### ISSUE TITLE
Mainline builds failing

### ISSUE THREAD

**Issue by dtcooper** [bkw777/mainline#174]
I know this may well not be the right place for this, but the [mainline PPA builds](https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=M;O=D) seem to be failing (or unavailable) since November 16. This means 6.1-rc6 and 6.1-rc7 are unavailable.

I have _no idea_ where to notify the developers (as the PPA is just a directory index), so I guess I post this here in hopes @bkw777 or someone else knows where we can let them know. Thanks!

**Comment by bkw777** [comment]
They know. There is no one to notify and nothing to do but wait. Somewhere on the ppa site there is some mention of an irc channel or mail list you have to register and join if you actually want to talk to them.

**Comment by dtcooper** [comment]
Okay, I'll search for the mailing list. Thanks @bkw777!
