### ISSUE TITLE
E: Operation not supported

### ISSUE THREAD

**Issue by alatteri** [bkw777/mainline#190]
` mainline --list --debug`

```
mainline 1.0.20
Distribution: Ubuntu 22.04.2 LTS
Architecture: amd64
Running kernel: 6.0.19-060019-generic
D: query_thread() App.show_prev_majors: 0
D: query_thread() App.hide_unstable: true
D: file_parent(/root/.cache/mainline/index.html)
D: dir_create(/root/.cache/mainline)
Fetching index from kernel.ubuntu.com...
E: Operation not supported
No updates found
----------------------------------------------------------------------
```

**Comment by rafalohaki** [comment]
mainline --list
mainline 1.0.20
Distribution: Ubuntu 22.04.2 LTS
Architecture: arm64
Running kernel: 5.15.0-1029-oracle
Fetching index from kernel.ubuntu.com...
E: Operation not supported

**Comment by cremesk** [comment]
i see the same issue here.

**Comment by omidfarhang** [comment]
Same happens here
```
mainline --list --debug
mainline 1.0.20
Distribution: Ubuntu 22.10
Architecture: amd64
Running kernel: 6.2.0-060200-generic
D: query_thread() App.show_prev_majors: 0
D: query_thread() App.hide_unstable: true
D: file_parent(/root/.cache/mainline/index.html)
D: dir_create(/root/.cache/mainline)
Fetching index from kernel.ubuntu.com...
E: Operation not supported
```

**Comment by piit79** [comment]
Yes, it most probably happens to everyone :) Let's not add any more "me too"s and hope for a quick fix. I unfortunately can't get myself to dig through a Vala source...

**Comment by bkw777** [comment]
It's not everyone, since it works fine for me.
It appears to be while trying to download index.html
And https://github.com/bkw777/mainline/pull/181 was merged just yesterday.

**Comment by bkw777** [comment]
Mean time, try downgrading to this commit:
https://github.com/bkw777/mainline/tree/8de5ac3b3f219cf69c11363edb7db913089bb32b

**Comment by LucasChollet** [comment]
This error is displayed by glib when there is no gvfs backend.
Do you have gvfs installed?

Does this output the same error?
```
gio info https://kernel.ubuntu.com/~kernel-ppa/mainline/
```

**Comment by mpiltz** [comment]
I did not have gvfs installed and  tested `gio info https://kernel.ubuntu.com/~kernel-ppa/mainline/` and it's output has the same error. 
After installing gvfs and running `mainline --list --debug` I got this response:
```
mainline 1.0.20
Distribution: Ubuntu 22.04.2 LTS
Architecture: amd64
Running kernel: 5.15.0-60-generic
D: query_thread() App.show_prev_majors: 0
D: query_thread() App.hide_unstable: true
D: file_parent(/home/userA/.cache/mainline/index.html)
D: dir_create(/home/userA/.cache/mainline)
Fetching index from kernel.ubuntu.com...
E: The specified location is not supported
```

**Comment by bkw777** [comment]
For the record, I do not intend for any new dependencies. It's fine to test just to find out what's going on, but in the end, the fix will not be "install gvfs".

**Comment by cremesk** [comment]
hi,

i also switch back to v1.0.19. now it works fine again.

FYI: I'm on Ubuntu 22.10 (gvfs is installed)

```
$ gio info https://kernel.ubuntu.com/~kernel-ppa/mainline/
display name: mainline
display name: mainline
type: regular
uri: https://kernel.ubuntu.com/~kernel-ppa/mainline/
attributes:
  standard::type: 1
  standard::display-name: mainline
  standard::edit-name: mainline
  standard::icon: text-html, text-x-generic, text-html-symbolic, text-x-generic-symbolic
  standard::content-type: text/html
  standard::fast-content-type: text/html
  standard::symbolic-icon: text-html-symbolic, text-x-generic-symbolic, text-html, text-x-generic
  id::filesystem: http:uri=https%3A%2F%2Fkernel.ubuntu.com%2F~kernel-ppa%2Fmainline%2F,prefix=%2F~kernel-ppa%2Fmainline
```

**Comment by mpiltz** [comment]
What is the best way to downgrade?

**Comment by bkw777** [comment]
If you're only using the ppa, I've reverted FileDownloader and bumped the version again, so wait a day and the ppa should update and you should get 1.0.21 naturally, which should work again.

**Comment by bkw777** [comment]
I think the internet connection check is also affected by this. That's a little bit messier to revert because means also reverting some other unrelated stuff, so in the short term, if you're having problems please check your settings and select "skip internet connection check". That way you simply avoid running the problem routine.

**Comment by bkw777** [comment]
Ok I just reverted the net connection check, so the ppa will get that shortly.

**Comment by mpiltz** [comment]
CLI is working and so is GUI after setting "skip internet connection check". Thank you for the quick fixes 👍🏻

**Comment by bkw777** [comment]
Good. When the ppa gets 1.0.22, that should be ok to re-enable the check if you want.

**Comment by bkw777** [comment]
Is everyone good? Can I close this?

**Comment by omidfarhang** [comment]
Latest update fixed it for me, working perfectly now.
