### ISSUE TITLE
amd64 build of mainline 1.1.0-0~202303050408~ubuntu18.04.1 in ubuntu bionic RELEASE

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#196]
valac  -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.1.0"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' -X -D'DEFAULT_PPA_URI="https://kernel.ubuntu.com/~kernel-ppa/mainline/"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 \
	src/Common/*.vala src/Utility/*.vala src/Console/*.vala -o mainline
src/Common/LinuxKernel.vala:199.28-199.31: error: `void' is not a supported generic type argument, use `?' to box value types
			var worker = new Thread<void>.try(null, () => query_thread((owned) notifier));
			                        ^^^^
src/Common/LinuxKernel.vala:199.28-199.31: error: `void' is not a supported generic type argument, use `?' to box value types
			var worker = new Thread<void>.try(null, () => query_thread((owned) notifier));
			                        ^^^^
src/Utility/AsyncTask.vala:137.16-137.19: error: `void' is not a supported generic type argument, use `?' to box value types
				new Thread<void>.try (null,read_stdout);
				           ^^^^
src/Utility/AsyncTask.vala:144.16-144.19: error: `void' is not a supported generic type argument, use `?' to box value types
				new Thread<void>.try (null,read_stderr);
				           ^^^^
Compilation failed: 4 error(s), 0 warning(s)

**Comment by bkw777** [comment]
Should be fixed by d8accb2
