### ISSUE TITLE
error compile on ubuntu 20.04 focal

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#21]
src/Gtk/TerminalWindow.vala:212.19-212.29: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
		term.feed_child(c.to_utf8());
		                ^^^^^^^^^^^

**Comment by bkw777** [comment]
Turns out that entire function is not used anywhere.
Fixed in https://github.com/bkw777/mainline/commit/7c9681af73e5fa02439503f5089b2e9abd73198d

**Comment by cappelikan** [comment]
NICE! 2 minute and focal package added to launchpad repository

вт, 21 квіт. 2020 о 02:41 Brian K. White <notifications@github.com> пише:

**Comment by cappelikan** [comment]
Please add to dialog translator me - "cappelikan (Ukrainian):
cappelikan@gmail.com",

вт, 21 квіт. 2020 о 04:39 Sergiy Golovko <cappelikan@gmail.com> пише:
