### ISSUE TITLE
Unloaded localization

### ISSUE THREAD

**Issue by venerdi2** [bkw777/mainline#212]
Translations of label "previous major versions" in(src/Gtk/SettingsDialog.vala:177) and
label "Internet connection timeout in" in (src/Gtk/SettingsDialog.vala:192) 
are not loaded into "Settings" window.

**Comment by bkw777** [comment]
I just went through all the strings in all the po files. Can you take another look?

**Comment by bkw777** [comment]
I tried ```LANGUAGE=ru_RU mainline-gtk``` and it looks complete to me.

**Comment by venerdi2** [comment]
Hello, this is the situation of the settings windows in italian.
Thank you for your work, Demetrio Mendozzi  

Il 03.04.2023 05:32 Brian
K. White ha scritto: 

> I tried LANGUAGE=ru_RU mainline-gtk and it
looks complete to me. 
> 
> --
> Reply to this email directly, view it
on GitHub [1], or unsubscribe [2].
> You are receiving this because you
authored the thread.Message ID: @github.com>
  


VOUCHER CONNETTIVITÀ per P.IVA e PMI: internet a canone 0 per 48 mesi. ATTIVA ORA
 https://casa.tiscali.it/promo/?u=https://promozioni.tiscali.it/voucher_business/?r=TS00000A00025&dm=link&p=tiscali&utm_source=tiscali&utm_medium=link&utm_campaign=voucherbusiness&wt_np=tiscali.link.footermail.voucherbusiness.btb..

**Comment by bkw777** [comment]
huh, you are correct, and it still does it on the latest version for it_IT
![image](https://user-images.githubusercontent.com/54458165/229623861-9cba6059-bacf-4c08-bb5f-e6e1cf45314d.png)
Looks like the po.it file is missing several entries. I'm filling them in with an online translator now.

**Comment by bkw777** [comment]
next update
![image](https://user-images.githubusercontent.com/54458165/229627170-67b9a208-0de6-4901-8adc-90fcedf1f1ff.png)
