### ISSUE TITLE
Reinstate "Changes" button but link goes straight to kernel-ppa changes location for target kernel

### ISSUE THREAD

**Issue by StatusCode404** [bkw777/mainline#223]
For many users of Mainlie, accessing the previous "changes" button was essential in determining whether to upgrade to that kernel version or not.  Clicking on the PPA button can work but requires more digging around in the fileserver to get to the right location.  So from a end-user usability perspective, removal of the function degraded the experience!

Why not reinstate the button but instead of having to cache the changes data, build the path to the exact link location where changes can be found for the target kernel version.  Thus nothing to cache.
e.g: 
https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1.21/CHANGES

The button could construct a path to create a link that will take it straight to the changes location in the kernel-ppa website.  
So the end-user gets to see the changes straight away.  Thus very little to no compromise is done and the experience and usability is retained.

**Comment by bkw777** [comment]
no

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline/discussions/224

**Comment by smith558** [comment]
This is a decrease in usability for me as well. Quite sad about it.

**Comment by bkw777** [comment]
PPA button. You didn't lose anything.

**Comment by smith558** [comment]
> PPA button. You didn't lose anything.

No one understood what the "PPA" button does until now. Now I know, but I didn't know before.

**Comment by bkw777** [comment]
In the discussion linked above I do wonder if maybe it needs a different label.
