### ISSUE TITLE
silent fail - no error message and install fails.

### ISSUE THREAD

**Issue by dreadedhamish** [bkw777/mainline#227]
Just trying Mainline for the first time.

Using the GUI and the CLI the following failed:
latest
6.2.10
6.2.9
6.2.8
In the CLI there is the progress using --debug:

Downloading 6.2.8
build_script():
working_dir: '/tmp/.mainline.e2G1vpS6'
aria2c --input-file='/tmp/.mainline.e2G1vpS6/download.list' --no-netrc=true --no-conf=true --summary-interval=1 --auto-save-interval=1 --enable-color=false --allow-overwrite --timeout=600 --max-file-not-found=3 --retry-wait=2 --show-console-readout=false --human-readable=false --connect-timeout=15 --max-concurrent-downloads=20 --max-connection-per-server=20
AsyncTask begin()
working_dir: '/tmp/.mainline.e2G1vpS6'

Afterwards no new kernel is installed or activated.
Ubuntu 22.10
mainline 1.2.3

**Comment by bkw777** [comment]
Could you please try `VERBOSE=4 mainline-gtk`
