### ISSUE TITLE
amd64 build of mainline 1.2.4-0~202304122308~ubuntu20.04.1 in ubuntu focal , bionic RELEASE

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#229]
focal 20.04 error build

make[1]: Entering directory '/<<PKGBUILDDIR>>'
valac  -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.2.4"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 \
	src/Common/*.vala src/lib/*.vala src/Console/*.vala -o mainline
src/Common/Main.vala:271.19-271.55: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				ppa_uri					=	config.get_string_member_with_default(		"ppa_uri",					DEFAULT_PPA_URI					);
				       					 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:272.20-272.56: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				all_proxy				=	config.get_string_member_with_default(		"all_proxy",				DEFAULT_ALL_PROXY				);
				         				 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:273.36-273.69: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				connect_timeout_seconds	=	(int)config.get_int_member_with_default(	"connect_timeout_seconds",	DEFAULT_CONNECT_TIMEOUT_SECONDS	);
				                       	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:274.33-274.66: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				concurrent_downloads	=	(int)config.get_int_member_with_default(	"concurrent_downloads",		DEFAULT_CONCURRENT_DOWNLOADS	);
				                    	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:275.23-275.60: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				hide_unstable			=	config.get_boolean_member_with_default(		"hide_unstable",			DEFAULT_HIDE_UNSTABLE			);
				             			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:276.30-276.63: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				previous_majors			=	(int)config.get_int_member_with_default(	"previous_majors",			DEFAULT_PREVIOUS_MAJORS			);
				               			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:277.22-277.59: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_major			=	config.get_boolean_member_with_default(		"notify_major",				DEFAULT_NOTIFY_MAJOR			);
				            			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:278.22-278.59: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_minor			=	config.get_boolean_member_with_default(		"notify_minor",				DEFAULT_NOTIFY_MINOR			);
				            			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:279.33-279.66: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_interval_unit	=	(int)config.get_int_member_with_default(	"notify_interval_unit",		DEFAULT_NOTIFY_INTERVAL_UNIT	);
				                    	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:280.34-280.67: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_interval_value	=	(int)config.get_int_member_with_default(	"notify_interval_value",	DEFAULT_NOTIFY_INTERVAL_VALUE	);
				                     	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:281.25-281.62: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				verify_checksums		=	config.get_boolean_member_with_default(		"verify_checksums",			DEFAULT_VERIFY_CHECKSUMS		);
				                		 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:282.27-282.60: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				window_width			=	(int)config.get_int_member_with_default(	"window_width",				DEFAULT_WINDOW_WIDTH			);
				            			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:283.28-283.61: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				window_height			=	(int)config.get_int_member_with_default(	"window_height",			DEFAULT_WINDOW_HEIGHT			);
				             			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:284.24-284.57: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				window_x				=	(int)config.get_int_member_with_default(	"window_x",					DEFAULT_WINDOW_X				);
				        				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:285.24-285.57: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				window_y				=	(int)config.get_int_member_with_default(	"window_y",					DEFAULT_WINDOW_Y				);
				        				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:286.26-286.59: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				term_width				=	(int)config.get_int_member_with_default(	"term_width",				DEFAULT_TERM_WIDTH				);
				          				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:287.27-287.60: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				term_height				=	(int)config.get_int_member_with_default(	"term_height",				DEFAULT_TERM_HEIGHT				);
				           				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:317.42-317.78: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				connect_timeout_seconds	=	int.parse(	config.get_string_member_with_default(	"connect_timeout_seconds",	DEFAULT_CONNECT_TIMEOUT_SECONDS	.to_string()	)	);
				                       	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:318.39-318.75: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				concurrent_downloads	=	int.parse(	config.get_string_member_with_default(	"concurrent_downloads",		DEFAULT_CONCURRENT_DOWNLOADS	.to_string()	)	);
				                    	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:319.35-319.71: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				hide_unstable			=	bool.parse(	config.get_string_member_with_default(	"hide_unstable",			DEFAULT_HIDE_UNSTABLE			.to_string()	)	);
				             			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:320.36-320.72: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				previous_majors			=	int.parse(	config.get_string_member_with_default(	"previous_majors",			DEFAULT_PREVIOUS_MAJORS			.to_string()	)	);
				               			 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:321.34-321.70: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_major			=	bool.parse(	config.get_string_member_with_default(	"notify_major",				DEFAULT_NOTIFY_MAJOR			.to_string()	)	);
				            			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:322.34-322.70: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_minor			=	bool.parse(	config.get_string_member_with_default(	"notify_minor",				DEFAULT_NOTIFY_MINOR			.to_string()	)	);
				            			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:323.39-323.75: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_interval_unit	=	int.parse(	config.get_string_member_with_default(	"notify_interval_unit",		DEFAULT_NOTIFY_INTERVAL_UNIT	.to_string()	)	);
				                    	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:324.40-324.76: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.4. Use json-glib-1.0 >= 1.6
				notify_interval_value	=	int.parse(	config.get_string_member_with_default(	"notify_interval_value",	DEFAULT_NOTIFY_INTERVAL_VALUE	.to_string()	)	);
				                     	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 25 error(s), 0 warning(s)
make[1]: *** [Makefile:67: mainline] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j1 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:20: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2023-04-13T04:35:44Z

Finished
--------
https://launchpadlibrarian.net/660951925/buildlog_ubuntu-focal-amd64.mainline_1.2.4-0~202304122308~ubuntu20.04.1_BUILDING.txt.gz

bionic 18.04 build error 

make[1]: Entering directory '/<<PKGBUILDDIR>>'
valac  -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.2.4"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 \
	src/Common/*.vala src/lib/*.vala src/Console/*.vala -o mainline
src/Common/Main.vala:271.19-271.55: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				ppa_uri					=	config.get_string_member_with_default(		"ppa_uri",					DEFAULT_PPA_URI					);
				       					 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:272.20-272.56: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				all_proxy				=	config.get_string_member_with_default(		"all_proxy",				DEFAULT_ALL_PROXY				);
				         				 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:273.36-273.69: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				connect_timeout_seconds	=	(int)config.get_int_member_with_default(	"connect_timeout_seconds",	DEFAULT_CONNECT_TIMEOUT_SECONDS	);
				                       	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:274.33-274.66: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				concurrent_downloads	=	(int)config.get_int_member_with_default(	"concurrent_downloads",		DEFAULT_CONCURRENT_DOWNLOADS	);
				                    	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:275.23-275.60: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				hide_unstable			=	config.get_boolean_member_with_default(		"hide_unstable",			DEFAULT_HIDE_UNSTABLE			);
				             			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:276.30-276.63: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				previous_majors			=	(int)config.get_int_member_with_default(	"previous_majors",			DEFAULT_PREVIOUS_MAJORS			);
				               			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:277.22-277.59: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_major			=	config.get_boolean_member_with_default(		"notify_major",				DEFAULT_NOTIFY_MAJOR			);
				            			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:278.22-278.59: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_minor			=	config.get_boolean_member_with_default(		"notify_minor",				DEFAULT_NOTIFY_MINOR			);
				            			 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:279.33-279.66: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_interval_unit	=	(int)config.get_int_member_with_default(	"notify_interval_unit",		DEFAULT_NOTIFY_INTERVAL_UNIT	);
				                    	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:280.34-280.67: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_interval_value	=	(int)config.get_int_member_with_default(	"notify_interval_value",	DEFAULT_NOTIFY_INTERVAL_VALUE	);
				                     	 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:281.25-281.62: error: `Json.Object.get_boolean_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				verify_checksums		=	config.get_boolean_member_with_default(		"verify_checksums",			DEFAULT_VERIFY_CHECKSUMS		);
				                		 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:282.27-282.60: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				window_width			=	(int)config.get_int_member_with_default(	"window_width",				DEFAULT_WINDOW_WIDTH			);
				            			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:283.28-283.61: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				window_height			=	(int)config.get_int_member_with_default(	"window_height",			DEFAULT_WINDOW_HEIGHT			);
				             			 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:284.24-284.57: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				window_x				=	(int)config.get_int_member_with_default(	"window_x",					DEFAULT_WINDOW_X				);
				        				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:285.24-285.57: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				window_y				=	(int)config.get_int_member_with_default(	"window_y",					DEFAULT_WINDOW_Y				);
				        				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:286.26-286.59: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				term_width				=	(int)config.get_int_member_with_default(	"term_width",				DEFAULT_TERM_WIDTH				);
				          				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:287.27-287.60: error: `Json.Object.get_int_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				term_height				=	(int)config.get_int_member_with_default(	"term_height",				DEFAULT_TERM_HEIGHT				);
				           				 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:317.42-317.78: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				connect_timeout_seconds	=	int.parse(	config.get_string_member_with_default(	"connect_timeout_seconds",	DEFAULT_CONNECT_TIMEOUT_SECONDS	.to_string()	)	);
				                       	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:318.39-318.75: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				concurrent_downloads	=	int.parse(	config.get_string_member_with_default(	"concurrent_downloads",		DEFAULT_CONCURRENT_DOWNLOADS	.to_string()	)	);
				                    	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:319.35-319.71: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				hide_unstable			=	bool.parse(	config.get_string_member_with_default(	"hide_unstable",			DEFAULT_HIDE_UNSTABLE			.to_string()	)	);
				             			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:320.36-320.72: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				previous_majors			=	int.parse(	config.get_string_member_with_default(	"previous_majors",			DEFAULT_PREVIOUS_MAJORS			.to_string()	)	);
				               			 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:321.34-321.70: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_major			=	bool.parse(	config.get_string_member_with_default(	"notify_major",				DEFAULT_NOTIFY_MAJOR			.to_string()	)	);
				            			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:322.34-322.70: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_minor			=	bool.parse(	config.get_string_member_with_default(	"notify_minor",				DEFAULT_NOTIFY_MINOR			.to_string()	)	);
				            			 	           	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:323.39-323.75: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_interval_unit	=	int.parse(	config.get_string_member_with_default(	"notify_interval_unit",		DEFAULT_NOTIFY_INTERVAL_UNIT	.to_string()	)	);
				                    	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Common/Main.vala:324.40-324.76: error: `Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2. Use json-glib-1.0 >= 1.6
				notify_interval_value	=	int.parse(	config.get_string_member_with_default(	"notify_interval_value",	DEFAULT_NOTIFY_INTERVAL_VALUE	.to_string()	)	);
				                     	 	          	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 25 error(s), 0 warning(s)
Makefile:67: recipe for target 'mainline' failed
make[1]: *** [mainline] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: make -j1 "INSTALL=install --strip-program=true" returned exit code 2
debian/rules:20: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2023-04-13T04:35:33Z

Finished
--------
https://launchpadlibrarian.net/660951926/buildlog_ubuntu-bionic-amd64.mainline_1.2.4-0~202304122308~ubuntu18.04.1_BUILDING.txt.gz

**Comment by bkw777** [comment]
sigh yeah I know what it is...

**Comment by bkw777** [comment]
hopefully fixed by da87de9
