### ISSUE TITLE
Include perf?

### ISSUE THREAD

**Issue by pfirsich** [bkw777/mainline#235]
Hello, my understanding of these things is not great, so I apologize if what I am asking for is stupid.
I went to a newer kernel to get newer io_uring features, but I need to use `perf` rather regularly. It seems the PPA does not have the corresponding `linux-tools-<version>-generic` package (`linux-tools-6.3.1-060301-generic` in my case). Is there a way to include those in the PPA? Apart from going back to my distro kernel, do I have another choice but to clone the kernel repo and build perf myself?

**Comment by bkw777** [comment]
Not an unreasonable question, but the answer is we don't create the packages. This is just a downloader-installer like synaptic or aptitude. All we do is download foo.deb and run dpkg -i foo.deb.

You would have to ask https://wiki.ubuntu.com/KernelTeam

**Comment by pfirsich** [comment]
That makes sense. Thanks for the response!
