### ISSUE TITLE
[Build #26279685] s390x build of mainline 1.3.10-0~202306060842~ubuntu20.04.1 in ubuntu focal RELEASE [~cappelikan/ubuntu/ppa]

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#247]
make[1]: Entering directory '/<<PKGBUILDDIR>>'
valac -D VTE_ASYNC  -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.3.10"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 \
	src/Common/*.vala src/lib/*.vala src/Console/*.vala -o mainline
valac -D VTE_ASYNC  -X -w -X -D'INSTALL_PREFIX="/usr"' -X -D'BRANDING_SHORTNAME="mainline"' -X -D'BRANDING_LONGNAME="Ubuntu Mainline Kernel Installer"' -X -D'BRANDING_VERSION="1.3.10"' -X -D'BRANDING_AUTHORNAME="Brian K. White"' -X -D'BRANDING_AUTHOREMAIL="b.kenyon.w@gmail.com"' -X -D'BRANDING_WEBSITE="https://github.com/bkw777/mainline"' -X -D'GETTEXT_PACKAGE="mainline"' --Xcc="-lm" \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg vte-2.91 --pkg x11 \
	src/Common/*.vala src/lib/*.vala src/Gtk/*.vala -o mainline-gtk
src/Gtk/TerminalWindow.vala:202.5-202.8: warning: Argument 6: Cannot pass null to non-null parameter type
				null, // child_setup() func
				^^^^
src/Gtk/TerminalWindow.vala:202.5-202.8: error: Argument 6: Cannot convert from `unowned null' to `int'
				null, // child_setup() func
				^^^^
src/Gtk/TerminalWindow.vala:203.5-203.6: error: Argument 7: Cannot convert from `int' to `unowned GLib.Cancellable?'
				-1, // timeout
				^^
src/Gtk/TerminalWindow.vala:196.4-206.4: error: 2 extra arguments for `void Vte.Terminal.spawn_async (Vte.PtyFlags, string?, string[], string[]?, GLib.SpawnFlags, int, GLib.Cancellable?)'
Compilation failed: 3 error(s), 1 warning(s)
make[1]: *** [Makefile:67: mainline-gtk] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j1 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:20: build-arch] Error 25
dpkg-buildpackage: error: debian/rules build-arch subprocess returned exit status 2

**Comment by bkw777** [comment]
fixed in 7496bde
Also repaired building back as far as xenial, so if you want, you should be able to enable building for xenial again in the ppa.
