### ISSUE TITLE
Latest commit (1.3.12-23-gd8fb007) doesn't download anymore...

### ISSUE THREAD

**Issue by Creteil** [bkw777/mainline#252]
<pre><font color="#26A269"><b>oem@oem-ThinkPad-P15-Gen-1</b></font>:<font color="#12488B"><b>~/tmp/Building/mainline</b></font>$ sudo mainline --list
mainline 1.3.13
Distribution: Ubuntu 22.04.2 LTS
Architecture: amd64
Running kernel: 6.3.6-060306-generic
Updating from: &apos;https://kernel.ubuntu.com/~kernel-ppa/mainline/&apos;
Found installed: linux-image-unsigned-6.3.6-060306-generic (running)
----------------------------------------------------------------
Available Kernels
----------------------------------------------------------------
6.3.7                          
6.3.6               Running    
6.3.5                          
6.3.4                          
6.3.3                          
6.3.2                          
6.3.1                          
6.3                            
6.2.16                         
6.2.15                         
6.2.14                         
6.2.13                         
6.2.12                         
6.2.11                         
6.2.10                         
6.2.9                          
6.2.8                          
6.2.7                          
6.2.6                          
6.2.5                          
6.2.4                          
6.2.3                          
6.2.2                          
6.2.1                          
6.2                            
6.1.33                         
6.1.32                         
6.1.31                         
6.1.30                         
6.1.28                         
6.1.27                         
6.1.26                         
6.1.25                         
6.1.24                         
6.1.23                         
6.1.22                         
6.1.21                         
6.1.20                         
6.1.19                         
6.1.18                         
6.1.17                         
6.1.16                         
6.1.15                         
6.1.14                         
6.1.13                         
6.1.12                         
6.1.11                         
6.1.10                         
6.1.9                          
6.1.8                          
6.1.7                          
6.1.6                          
6.1.5                          
6.1.4                          
6.1.2                          
6.1.1                          
6.1                            
6.0.19                         
6.0.18                         
6.0.17                         
6.0.16                         
6.0.15                         
6.0.14                         
6.0.13                         
6.0.12                         
6.0.11                         
6.0.10                         
6.0.9                          
6.0.8                          
6.0.7                          
6.0.6                          
6.0.5                          
6.0.4                          
6.0.3                          
6.0.1                          
6.0                            
<font color="#26A269"><b>oem@oem-ThinkPad-P15-Gen-1</b></font>:<font color="#12488B"><b>~/tmp/Building/mainline</b></font>$ sudo mainline --install 6.3.7
mainline 1.3.13
Distribution: Ubuntu 22.04.2 LTS
Architecture: amd64
Running kernel: 6.3.6-060306-generic
Updating from: &apos;https://kernel.ubuntu.com/~kernel-ppa/mainline/&apos;
Found installed: linux-image-unsigned-6.3.6-060306-generic (running)
Installing selected kernels:
Requested 6.3.7

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_item_construct: assertion &apos;cksum != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_task_add_to_queue: assertion &apos;item != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_item_construct: assertion &apos;cksum != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_task_add_to_queue: assertion &apos;item != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_item_construct: assertion &apos;cksum != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_task_add_to_queue: assertion &apos;item != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_item_construct: assertion &apos;cksum != NULL&apos; failed

** (process:120386): <font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">12:30:58.301</font>: download_task_add_to_queue: assertion &apos;item != NULL&apos; failed
Downloading 6.3.7
6.3.7! download failed.                                                        
Install: no installable kernels specified
<font color="#26A269"><b>oem@oem-ThinkPad-P15-Gen-1</b></font>:<font color="#12488B"><b>~/tmp/Building/mainline</b></font>$</pre>

**Comment by bkw777** [comment]
Bonehead move on my part. fix in a few minutes.
What you can doin the short term is go into settings and enable the CHECKSUMS option.

I removed a line that was populating an array with ""s right after clearing it. I forgot the point was to ensure that the elements were at least "" and not null even if they don't get filled with checksums from the checksums file.

I happen to have that checksums setting enabled while I'm testing so it kept working for me.

**Comment by bkw777** [comment]
actually 15f1b69
