### ISSUE TITLE
State: Failed to build

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#275]
mkdir -p "/<<PKGBUILDDIR>>/debian/mainline/usr/share/locale/${l}/LC_MESSAGES"; \
	msgfmt --check --verbose -o "/<<PKGBUILDDIR>>/debian/mainline/usr/share/locale/${l}/LC_MESSAGES/mainline.mo" ${p}; \
done
de: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
el: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
es: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
fr: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
hr: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
it: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
ko: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
nl: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
pl: 133 translated messages, 7 fuzzy translations, 9 untranslated messages.
ru: 149 translated messages.
sv: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
tr: 82 translated messages, 29 fuzzy translations, 38 untranslated messages.
uk: po/uk.po:674:68: syntax error
msgfmt: found 1 fatal error
make[1]: *** [Makefile:143: install] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_install: error: make -j4 install DESTDIR=/<<PKGBUILDDIR>>/debian/mainline AM_UPDATE_INFO_DIR=no returned exit code 2
make: *** [debian/rules:5: binary-arch] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary-arch subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2023-06-28T11:38:01Z

**Comment by bkw777** [comment]
uk.po, you broke uk.po again.
Why do you keep doing that?

**Comment by bkw777** [comment]
Another user fixed it this time. Other times I fixed it before merging, then this time I tried to make you fix it and I thought you had, and it looked ok in github but I didn't actually try to build it, so it got through.

**Comment by bkw777** [comment]
fixed
