### ISSUE TITLE
Change Setting Window Resolution

### ISSUE THREAD

**Issue by Danik2343** [bkw777/mainline#290]
Add ability to change setting window resolution

**Comment by Danik2343** [comment]
And add scroller for settings windows

**Comment by bkw777** [comment]
I'm going to convert the single settings window to a pages style where there is a seperate page for each of the sections, so each page will just have a couple of related settings like Network, or Filters, which will make the window much smaller.

**Comment by bkw777** [comment]
Not exactly what you asked for but I think 95259fd addresses the same problem a different way.
