### ISSUE TITLE
Kernel Locked ?

### ISSUE THREAD

**Issue by abdelouahabb** [bkw777/mainline#310]
Installed 6.4.12 kernel and now I can't uninstall it because it says it's locked : 
![Screenshot from 2023-08-30 10-36-07](https://github.com/bkw777/mainline/assets/2527234/4aa93e5c-110c-4160-bf28-4d4b25519f72)

**Comment by bkw777** [comment]
In the gui there is a column called "lock". You can toggle any kernel to lock/unlock it. You probably clicked on it unintentionally. Just run the gui and toggle it back off.
