### ISSUE TITLE
Kubuntu 23.04 - cannot install 6.4.13 (previous 6.4.x kernels are fine) ...  depends on libc6 (>= 2.38)

### ISSUE THREAD

**Issue by morgancoxuk** [bkw777/mainline#312]
Hi.

I am using mainline on kubuntu 23.04, it has been fine until now, I have installed 6.3.x and 6.4.x kernels with no issue.

Today however i tried to install 6.4.13 and install fails due to 

```
setting up linux-headers-6.4.13-060413 (6.4.13-060413.202308301431) ...
dpkg: dependency problems prevent configuration of linux-headers-6.4.13-060413-generic:
 linux-headers-6.4.13-060413-generic depends on libc6 (>= 2.38); however:
  Version of libc6:amd64 on system is 2.37-0ubuntu2.
```

How can i get round this ?

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline/issues/311

**Comment by bkw777** [comment]
Updated readme.
https://github.com/bkw777/mainline#kernels-with-broken-dependencies
