### ISSUE TITLE
libc6 broken depenency

### ISSUE THREAD

**Issue by tsipo** [bkw777/mainline#317]
As of 6.5 or 6.51, the headers package fails to install as it has broken dependency on libc6 (Ubuntu 22.04.3 with all standard packages up-to-date). Example with 6.5.3:

> mainline 1.4.8
install 6.5.3 
...
Downloading 6.5.3
Installing 6.5.3                                                      
...
Setting up linux-headers-6.5.3-060503 (6.5.3-060503.202309130834) ...
dpkg: dependency problems prevent configuration of linux-headers-6.5.3-060503-generic:
 linux-headers-6.5.3-060503-generic depends on libc6 (>= 2.38); however:
  Version of libc6:amd64 on system is 2.35-0ubuntu3.3.
dpkg: error processing package linux-headers-6.5.3-060503-generic (--install):
 dependency problems - leaving unconfigured
...
done
Errors were encountered while processing:
 linux-headers-6.5.3-060503-generic
mainline: done

Running apt fix-broken removes the headers package:
>$ sudo apt install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  linux-headers-6.5.3-060503-generic

libc6 packages:
> $ sudo apt list --installed | grep libc6
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
libc6-dbg/jammy-updates,now 2.35-0ubuntu3.3 amd64 [installed,automatic]
libc6-dev/jammy-updates,now 2.35-0ubuntu3.3 amd64 [installed,automatic]
libc6/jammy-updates,now 2.35-0ubuntu3.3 amd64 [installed,automatic]

The new kernel can start with no problem BTW, but the headers package is missing.

**Comment by akronym0** [comment]
The only purpose of this app is basically to let users download the list of available kernels from http://kernel.ubuntu.com/~kernel-ppa/mainline/ and install a kernel from the list.

Unfortunately, the latest kernel packages in the Mainline ppa are not compatible with the current Ubuntu LTS version anymore. You would have to convince the Mainline kernel team to include support for older Ubuntu versions. But that has been tried many times already without success.

See also https://ubuntuforums.org/showthread.php?t=2490234

**Comment by tsipo** [comment]
Thank you, I will close the issue then.
