### ISSUE TITLE
Missing 6.1.54 

### ISSUE THREAD

**Issue by BarbzYHOOL** [bkw777/mainline#318]
Hello, I want to try to downgrade to the stablest kernel available so I look at https://www.kernel.org/ and see 6.1.54 but it's missing in mainline, it stops at 6.1.53

Why?

Offtopic: is it possible for me to use kernel 5.x.x even though my distribution never ran on this and only ran on 6.x.x?

**Comment by bkw777** [comment]
From the main readme under FAQ: https://github.com/bkw777/mainline?missing-kernels=#missing-kernels

Not all upstream kernel.org kernels have matching valid ubuntu.kernel.com successful .deb package builds.
This app does not build the kernel packages, and has no relationship with the people that do. It just downloads and installs .deb packages from ubuntu.kernel.com (not www.kernel.org).

Press the "PPA" button and scroll down to 6.1.53, and you will see that that version was a failed build for amd64.
If you want to see all possible versions, including ones that don't actually exist or aren't installable, you can un-select "hide failed or incomplete builds" in settings.

You can try to run any version you want. Maybe it works, maybe it doesn't.

**Comment by BarbzYHOOL** [comment]
thank you
