### ISSUE TITLE
Not show any kernel

### ISSUE THREAD

**Issue by johnnynunez** [bkw777/mainline#320]
![image](https://github.com/bkw777/mainline/assets/22727137/a317591e-7736-44a9-b690-3421499caabd)

**Comment by Thedemon007** [comment]
i think are ralationed with 404 error in this url: https://kernel.ubuntu.com/~kernel-ppa/mainline/

**Comment by Imnotndesh** [comment]
Experiencing the same problem

**Comment by cherepanov** [comment]
looks like they just moved to another path

https://kernel.ubuntu.com/mainline/

**Comment by Imnotndesh** [comment]
Oh yeah..thanks

**Comment by bkw777** [comment]
Hm, pr didn't do the whole job. Still need to update the previously stored url in the config file. I'm on it.

**Comment by bkw777** [comment]
Fixed in 1.4.9
