### ISSUE TITLE
why is main line not showing updates

### ISSUE THREAD

**Issue by Phillip-Dunstall** [bkw777/mainline#324]
why is main line not showing updates as kernels 6.5.8 & 6.5.9 & 6.6.0 and now 6.6.1 have been released

https://github.com/bkw777/mainline/assets/3252950/472949de-5b7d-40ba-b2da-97d16ed125b0

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline#help--faq
Particularly: https://github.com/bkw777/mainline#missing-kernels
In this case, those versions are not merely failed builds but not built at all.
Why not? Who knows. I don't build the .deb packages, the ubuntu kernel team does.
