### ISSUE TITLE
Use Meson build system

### ISSUE THREAD

**Issue by stsdc** [bkw777/mainline#34]
Meson is now a standard for Gtk apps.

**Comment by bkw777** [comment]
Why do we care what any other project uses for it's build system?
Feel free to port the makefile to meson and wow me with how much better it is. If it is actually any better in any substantive way, and does everything the current makefile does, and doesn't come with some annoying new requirements for no outward benefit, I'll probably be happy to adopt it. Perhaps you can detect which way I'm biased though ;)

**Comment by stsdc** [comment]
Having troubles to compile using meson. Wondering if there is special valac flag :thinking: 
![obraz](https://user-images.githubusercontent.com/6031763/83056608-06352800-a056-11ea-89bf-d766489d06e5.png)

**Comment by stsdc** [comment]
oh, there are two targets

**Comment by stsdc** [comment]
So I started #37. It will be nice. It will allow to use all these gresources and icons very easily. Hope it will simplify project maintenance.
