### ISSUE TITLE
RFE: apt-get source linux-source-6.11.0-061100rc2-generic

### ISSUE THREAD

**Issue by rcpao** [bkw777/mainline#343]
Add a button to download the source code for the selected kernel with Ubuntu config and patches please.  I need to tweak a few CONFIGs and recompile just one set of kernel driver modules.  Thank you.

**Comment by bkw777** [comment]
There are no source nor patch packages, only a pointer to a mainline git commit hash in the html page for each packaged version.
IE: highlight a kernel, press PPA, read:

These binary packages represent builds of Mainline Test tree at the commit below:

  cod/mainline/v6.10.6 (22859757db31c5aa6a0691abdb574f001b06772f)

To obtain the source from which they are built fetch the commit below:

  git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack cod/mainline/v6.10.6

Managing git clones is not something I want to get into. This app just downloads/installs/uninstalls .deb packages.
