### ISSUE TITLE
Mainline Kernels 6.8 thru 6.10 won't build latest Nvidia Drivers

### ISSUE THREAD

**Issue by hackdefendr** [bkw777/mainline#344]
I don't know where else to start. None of the mainline kernel header packages from version 6.8 thru 6.10 will compile the Nvidia kernel module. I have spent 3 days on this and it just does not work with mainline kernels. I even tried different GCC versions 13 and 14, where v14 completely crashes my server with OOM errors until it just powers off.

Here's the nvidia-installer log file from the Nvidia .run installer on the latest 6.8 mainline kernel:

[nvidia-installer.log](https://github.com/user-attachments/files/16718807/nvidia-installer.log)

Note: When I boot into the stable default kernel, everything works.

**Comment by bkw777** [comment]
Correct.

**Comment by nbohr1more** [comment]
Mainline kernels aren't signed so signed nvidia drivers cannot be integrated with them
