### ISSUE TITLE
Kernels after 6.11 do not show up in the list

### ISSUE THREAD

**Issue by tomastan** [bkw777/mainline#345]
Even if list refresh the last mainline kernel to display is 6.11:

![image](https://github.com/user-attachments/assets/1c5033f7-1b40-4afc-9694-865e422436fb)

While the mainline list on the server includes 6.11.x and 6.12 
![image](https://github.com/user-attachments/assets/a988b66d-faf2-4009-aa59-3f2fcd51d9e6)

Something looks to be broken.

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline?tab=readme-ov-file#missing-kernels
