### ISSUE TITLE
Error trying to install v5.7

### ISSUE THREAD

**Issue by rscm** [bkw777/mainline#41]
Hi

I can't install the latest kernel version 5.7, I tried downloading it manually from the website using the browser and it works.

**Debug Log**
$ mainline --install-latest --debug --yes > error_mainline_5.7.log
[error_mainline_5.7.log](https://github.com/bkw777/mainline/files/4733695/error_mainline_5.7.log)
(just changed my home dir with $HOME)

If you need more info just ask

Bye

**Comment by loran750** [comment]
hello

same for me, not in bash but by launching Mainline app in Ubuntu

![image](https://user-images.githubusercontent.com/2526608/83859683-8e828f80-a71e-11ea-829a-98542bd1f83c.png)


regards

**Comment by bkw777** [comment]
I haven't debugged this, but just from looking at the version number, it looks like I probably introduced a bug recently in the way the version strings are reformatted and used internally.
The debug output isn't showing the actual urls, but I bet what's going on is it's trying to construct urls where the path component says "/v5.7.0/" instead of "/v5.7/"

As it happens, I just happen to be already just about done re-writing from scratch the way the different version strings that come from different sources are parsed, and how the lists of kernel versions and installed packages and installable deb files are built.

This error should be cleared up naturally as part of that update.

Seperately, I suspect, once 5.7.1 comes out, even the current buggy version will work again, because the version number and the ppa directory name will have the 3rd part again like "/v5.7.1/". So even if I don't have the update ready as fast as I think, the problem will still probably go away anyway until 5.8.0.

Sorry about that.

**Comment by lelecanfora** [comment]
similar issue, different error:
`/usr/bin/env: cannot change directory to '/home/user/.cache/mainline/5.7.10/amd64': No such file or directory`

**Comment by tlhunter** [comment]
I get the same errors. Seems like Mainline isn't able to update to the current stable release on the current Ubuntu distro:

```
mainline 1.0.12
Distribution: Ubuntu 20.04.1 LTS
Architecture: amd64
Running kernel: 5.4.0-42-generic
----------------------------------------------------------------------
Found installed: 5.4.0-31.35
Found installed: 5.4.0-42.46
Found installed: 5.4.0.42.45
----------------------------------------------------------------------
----------------------------------------------------------------------

Downloading: 'amd64/linux-modules-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb'... 
49.0 MB / 52.7 MB, 2.7 MB/s (1s)                            
(process:126158): GLib-GIO-CRITICAL **: 10:36:24.540: g_output_stream_clear_pending: assertion 'G_IS_OUTPUT_STREAM (stream)' failed
E: Error moving file /tmp/.mainline_arzvOcC8/linux-modules-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb: No such file or directory
E: Failed to move file: '/tmp/.mainline_arzvOcC8/linux-modules-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb' → '/home/tlhunter/.cache/mainline/5.7.10/amd64/amd64/linux-modules-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb'
ERROR                                                                 

Downloading: 'amd64/linux-headers-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb'... 
426.0 KB / 1.2 MB, 381.0 KB/s (2s)                          
(process:126158): GLib-GIO-CRITICAL **: 10:36:27.681: g_output_stream_clear_pending: assertion 'G_IS_OUTPUT_STREAM (stream)' failed
E: Error moving file /tmp/.mainline_ZHa8B3ny/linux-headers-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb: No such file or directory
E: Failed to move file: '/tmp/.mainline_ZHa8B3ny/linux-headers-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb' → '/home/tlhunter/.cache/mainline/5.7.10/amd64/amd64/linux-headers-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb'
ERROR                                                                 

Downloading: 'amd64/linux-headers-5.7.10-050710_5.7.10-050710.202007220834_all.deb'... 
OK                                                                    

Downloading: 'amd64/linux-image-unsigned-5.7.10-050710-generic_5.7.10-050710.202007220834_amd64.deb'... 
OK                                                                    

Close window to exit...
```

Plenty of disk space:

```
$ df /
Filesystem                 1K-blocks      Used Available Use% Mounted on
/dev/mapper/vgkubuntu-root 477410176 188174988 264914372  42% /
$ df /boot
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/sda2         721392 209572    459356  32% /boot
```

**Comment by kaincenteno** [comment]
weird i'm not having this issue. Was able to install kernel 5.8

**Comment by mexin** [comment]
> similar issue, different error:
> `/usr/bin/env: cannot change directory to '/home/user/.cache/mainline/5.7.10/amd64': No such file or directory`

I'm getting this same error when trying 5.8.0, any way to fix?

**Comment by tlhunter** [comment]
Hmm, now that I think of it, maybe run `mkdir -p ~/.cache/mainline/5.7.10/amd64` first

**Comment by mexin** [comment]
Tried on 5.8.0 and created the 'amd64' folder but not I'm getting
`dpkg: error: --install needs at least one package archive file argument`
So it seems it's not retrieving the .deb files

**Comment by mexin** [comment]
Update: Removing index.html from the 5.8.0 folder solved it for me. Removed the filed and refreshed then I was able to download it and install it

**Comment by pppov** [comment]
I had this same error on trying to install 5.8.4 
`/usr/bin/env: cannot change directory to '/home/user/.cache/mainline/5.8.4/amd64': No such file or directory`
But the directory was there. But there was a text file in it called 'invalid' with just '1 0' in it. I deleted the file, refreshed and the kernel installed normally.

**Comment by bkw777** [comment]
There's a couple different errors in this thread. The actual reported issue was fixed some time ago. The other issue about changing to a directory was fixed just recently as part of something else.
