### ISSUE TITLE
[Feature] Add "Clear cache" button

### ISSUE THREAD

**Issue by tovam** [bkw777/mainline#45]
That would be useful to add a clear cache button for when "cache poisoning" happens, like with #43 
Maybe not top priority as the tool targets power users but still quite practical I think

Edit: I just realized there is a "--clean-cache" command but I still think it would be nice to have a button

**Comment by bkw777** [comment]
I agree.

I have a branch locally (which does not work and is a complete disaster, so it's not pushed) where I'm refactoring the version number parsing and logic and adding some new config settings and removng a ton more unused code left over from the teejee utils. I ran in to so many unexpected things that needed re-arranging that that branch ended up a train wreck with too many changes at once, but now that I hit all that stuff at least I think I have an idea how to go about it better a 2nd time, what kinds of things to change in smaller stand-alone commits that keep things working while changing.

So while I won't seem to do anything about this immediately, it's a perfect kind of thing to add along the way in this refactor, or after. Call this in the queue.

**Comment by bkw777** [comment]
Done. The new "Reload" button deletes the cache.
21958b3
