### ISSUE TITLE
weird behavior install kernel

### ISSUE THREAD

**Issue by BelphegorPrime** [bkw777/mainline#49]
![Screenshot from 2020-07-15 15-59-47](https://user-images.githubusercontent.com/3178520/87554425-69395780-c6b4-11ea-8968-cdc948f88731.png)

as you can see, the current kernel is 5.7.8-050708 but it is not listed in the kernel list.
When I try to install the Kernel im already running I get this error.

**Comment by bkw777** [comment]
Does the Refresh button change anything?

**Comment by BelphegorPrime** [comment]
negative

**Comment by BelphegorPrime** [comment]
Interesting is, that installing 5.7.9 works like a charm but trying to install 5.7.8 hit with the same error.

![Screenshot from 2020-07-17 15-13-23](https://user-images.githubusercontent.com/3178520/87789949-1db3b480-c840-11ea-9596-3a3bda17a50d.png)

**Comment by bkw777** [comment]
This seems to be fixed somewhere along the way, probably by better detection and rejection of kernels that didn't actually build successfully. Impossible to debug now, as there is no 5.7.8 at all on the mainline ppa web site.
