### ISSUE TITLE
Disambiguate the Purge button.

### ISSUE THREAD

**Issue by k3dar** [bkw777/mainline#50]
purge not remove selected kernel but all (without running and latest)...

if i select example "5.7.6" and click to "Purge" button, then is not purge only "5.7.6",
but ask for remove all kernel without one running and latest (if is newer that running)...

if i use Remove button then work fine, remove selected kernel, but of course keep is listed as "^rc" in "dpkg -l"

output from Purge:
```
mainline 1.0.12
Distribution: Ubuntu 18.04.4 LTS
Architecture: amd64
Running kernel: 5.7.8-050708-generic
----------------------------------------------------------------------
Found installed: 5.3.0.62.115
Found installed: 5.3.18-050318.201912181133
Found installed: 5.7.8-050708.202007090835
Found installed: 5.7.9-050709.202007160732
Found installed: 5.7.6-050706.202006241631
Found installed: 5.3.0-62.56~18.04.1
Found installed: 5.7.7-050707.202007010943
----------------------------------------------------------------------
----------------------------------------------------------------------

The following kernels will be removed::
 ▰ 5.7.7
 ▰ 5.7.6
 ▰ 5.3.18
 ▰ 5.3.0.62.56
 ▰ 5.3.0.62

Continue ? (y/n): 

```

**Comment by bkw777** [comment]
That's what purge does.
"Remove installed kernels older than running kernel"

**Comment by k3dar** [comment]
Although "purge" is normaly (in packages contents) used as:
_purge is identical to remove except that packages are removed and purged (any configuration files are deleted too)._
I now undersand, then question: can you please add/change question in "Purge" dialog also only selected kernel?
Or change behaviour, if nor kernel selected, Purge as now, if selected Purge only selected? Thanks ;-)

**Comment by bkw777** [comment]
What other word do you suggest to label that button?
What config files are left behind when removing a kernel package currently?

**Comment by bkw777** [comment]
No answer to my questions.

**Comment by k3dar** [comment]
Sorry for latter reply...

> What other word do you suggest to label that button?

i sugest this:

1. keep "Remove" button named as is, but change internal bahaviour from "apt remove" to "apt purge"
if you don't have separated Button for Remove and Purge then is i think ok keep
named purge function as "Remove"

2. change "Purge" button to "Remove Old", and also change behaviour from remove to purge.

> What config files are left behind when removing a kernel package currently?

example, now i "Remove" in "mainline" kernel 5.8.1, and because is removed not purged:
```
$ dpkg -l | grep 5.8.1-0
rc  linux-image-unsigned-5.8.1-050801-generic   5.8.1-050801.202008111432     amd64     Linux kernel image for version 5.8.1 on 64 bit x86 SMP
rc  linux-modules-5.8.1-050801-generic          5.8.1-050801.202008111432     amd64     Linux kernel extra modules for version 5.8.1 on 64 bit x86 SMP

$ dpkg -L linux-image-unsigned-5.8.1-050801-generic
Package 'linux-image-unsigned-5.8.1-050801-generic' does not contain any files (!)

$ dpkg -L linux-modules-5.8.1-050801-generic
/lib
/lib/modules
/lib/modules/5.8.1-050801-generic

$ ls -l /lib/modules/5.8.1-050801-generic
total 5580
-rw-r--r-- 1 root root 1418392 Aug 25 05:58 modules.alias
-rw-r--r-- 1 root root 1397618 Aug 25 05:58 modules.alias.bin
-rw-r--r-- 1 root root   25773 Aug 25 05:58 modules.builtin.alias.bin
-rw-r--r-- 1 root root   12521 Aug 25 05:58 modules.builtin.bin
-rw-r--r-- 1 root root  648633 Aug 25 05:58 modules.dep
-rw-r--r-- 1 root root  899094 Aug 25 05:58 modules.dep.bin
-rw-r--r-- 1 root root     314 Aug 25 05:58 modules.devname
-rw-r--r-- 1 root root     853 Aug 25 05:58 modules.softdep
-rw-r--r-- 1 root root  575801 Aug 25 05:58 modules.symbols
-rw-r--r-- 1 root root  705788 Aug 25 05:58 modules.symbols.bin


```

**Comment by bkw777** [comment]
Thanks, this makes sense.

**Comment by bkw777** [comment]
Done.
29dcea3  
6412181
