### ISSUE TITLE
Need to load Kernel first

### ISSUE THREAD

**Issue by LHRaceIng** [bkw777/mainline#53]
Hey everyone,
Although my issue is probably not directly related to the Mainline Kernel Installer, i am hoping to find some help over here.

Main issue:
I am running Ubuntu 20.04LTS in Dual Boot with Windows and trying to install the Kernel 5.7.0. Installation works fine and i can select the new Kernel in the advanced option Menu when rebooting but then i always get the error: 

Loading Linux 5.7.0-050700-generic …
error: /boot/vmlinuz-5.7.0-050700-generic has invalid signature.
Loading initial ramdisk …
error: you need to load the kernel first.

Press any key to continue…_

I already tried out different Kernels but always getting the same message. Maybe someone more experienced can help me out?
Would really appreciate it!

**Comment by LHRaceIng** [comment]
Okay i fixed it.
Disable secure Boot in BIOS.

**Comment by dandv** [comment]
It would *really* help if the tool advised the user to remember to disable SecureBoot.
