### ISSUE TITLE
The "status" row in mainline-gtk is not in sync when CLI mainline was used to install kernel

### ISSUE THREAD

**Issue by 8GM-DK** [bkw777/mainline#61]
As I understand it, the "status" row in mainline-gtk should show "installed" for the (currently running) 5.8.10 kernel that was installed using mainline on the CLI. It does show "Running 5.8.10-050810" in the bottom status field, but in the list of kernels, 5.8.10 has no status entry.

![grafik](https://user-images.githubusercontent.com/18285531/94113376-1532b800-fe47-11ea-88bc-6f59cbd75f47.png)

**Comment by bkw777** [comment]
Apologies. It's a bug alright.

**Comment by bkw777** [comment]
I think this must have been fixed somewhere along the way as a natural consequence of other updates. I can't duplicate it now.
