### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by pedro2555** [bkw777/mainline#62]
Really appreciate the continuation of this project as a GPL licensed software.

Add a donate button please, I'll send you 20$.

**Comment by bkw777** [comment]
That is very generous of you, but there is no need. I intentionally removed all the donate stuff from the original version. Thank you very much for offering though.

**Comment by cldellow** [comment]
Piling on to this closed issue to say: thank you for maintaining this!

Whenever I buy a new laptop for work, it seems I always hit some hardware issue. The stock Ubuntu 20.04 kernel (5.8.0.43) _almost_ had all the patches I needed backported to it, but alas, one hadn't landed yet.

mainline made it so painless to move to 5.11, which fixed all of my hardware issues. Thank you!
