### ISSUE TITLE
repository on ubuntu groovy gorilla 404

### ISSUE THREAD

**Issue by jbpallingayan** [bkw777/mainline#65]
rr:10 http://ppa.launchpad.net/cappelikan/ppa/ubuntu groovy Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/cappelikan/ppa/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by noah1510** [comment]
I have a goovy build in my [ppa](https://launchpad.net/~noasakurajin/+archive/ubuntu/useful-tools) it is a daily build of the same mirror as the cappelikan ppa. (The ppa also contains other daily build packages like mangohud)

**Comment by noah1510** [comment]
At the moment there is a different problem with grrovy builds.
I get the following warning: 
` Compatibility levels before 10 are deprecated (level 9 in use) `

So the contents of debian/compat have to be changed to 10 or higher to continue working with future ubuntu versions.

**Comment by Seltonu** [comment]
![image](https://user-images.githubusercontent.com/10287568/102639839-726c9b80-410e-11eb-8978-6f52f7f7eb82.png)

getting the same issue, mainline is uninstallable on groovy (PopOS 20.10)

**Comment by bkw777** [comment]
I build with "make deb" (which uses pbuilder-dist) on groovy with no such error. The releases tab here on github has a .deb  However when i change compat to 10, it does fail. So something else needs to be changed to satisfy whatever all the rules are that define compat level 10.

**Comment by noah1510** [comment]
@Seltonu you get the error because the cappelican ppa does not build for groovy at the moment. If you need groovy or hirsute you can use [this](https://launchpad.net/~noasakurajin/+archive/ubuntu/useful-tools) ppa until the cappelikan is updated to also build for groovy and hirsute.

**Comment by Seltonu** [comment]
thanks for the pointer! I'll probably wait it out, as I feel installing software from non-"official" ppa's is a bad rabbit hole to go down security wise. I'd be happy to provide any testing I can help with

**Comment by noah1510** [comment]
@bkw777 The error is produced by calling debuild. You can check [this](https://launchpadlibrarian.net/511948755/buildlog.txt.gz) buildlog on launchpad of the latest mainline build. The error message seems to suggest that compatibility level 9 will be removed in a point in the future (probably the next LTS release).

**Comment by noah1510** [comment]
>  feel installing software from non-"official" ppa's is a bad rabbit hole to go down security wise. I'd be happy to provide any testing I can help with

@Seltonu the built sources are exactly the same as the one on the cappelikan ppa even the same recepie, just published on a different ppa and there are other packages in the ppa

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline/issues/74

**Comment by connectety** [comment]
There is a groovy build in the [cappelikan ppa](https://code.launchpad.net/~cappelikan/+archive/ubuntu/ppa).
The debian 10 compatibility may still be a problem, but that has its own issue. 
@bkw777  Maybe this can be closed.
