### ISSUE TITLE
Not updating beyond 5.9.8

### ISSUE THREAD

**Issue by IulianDita** [bkw777/mainline#67]
Heya.

Thanks for the great work!

Starting with version 5.9.8, it's no longer updating on my machine (HP ProBook 445 G7, Ubuntu 20.04).
I can see the entries (all the way to 5.9.11), I don't get any error, it's downloading and everything, but the new kernel is not available to boot from or present in /boot.

Here's what Mainline tells me:
![image](https://user-images.githubusercontent.com/4585657/100358381-681b1e00-2ff6-11eb-82b8-06a3ac2306c3.png)

Enough free space on all partitions, including /boot...
Any ideas? Where can I find some logs?

**Comment by tuongdn** [comment]
HP Elitebook 835 G7 & Ubuntu 20.04, same issue. Installation ends after setting up Linux header, without downloading module or modifying GRUB.

**Comment by Matoran** [comment]
Have you tried `mainline --install 5.9.10`?  5.9.11 build failed currently: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.11/amd64/

**Comment by IulianDita** [comment]
Well, would you look at that. Indeed, both 5.9.9 and 5.9.11 are broken (rc=2), and these are the ones that fail in both the app and in the terminal. 5.9.10 installed just fine. Thank you!

**Comment by IulianDita** [comment]
Just an idea, just don't show these in Mainline, or add a warning that the build are broken for your architecture?
