### ISSUE TITLE
Filtered default view?

### ISSUE THREAD

**Issue by pigsflew** [bkw777/mainline#68]
I'd love to have a way to filter the list so it will only show me, for example:

- The latest available mainline kernel
- All currently installed kernels
- The latest available mainline kernel for each major.minor kernel version installed.

Essentially I'd love to see like a tree view that has those things visible by default, and other versions show up with a filter. Something like the below, visible all at once in the main pane:

> ## 5.9 (latest, not installed)
> - [ ] 5.9.12 (mainline, latest)
> ## 5.8
> - [ ] 5.8.18 (mainline, latest)
> - [x] 5.8.0-31.33 (official, running)
> ## 5.4
> - [ ] 5.4.81 (mainline, latest)
> - [x] 5.4.72 (mainline)
> - [x] 5.4.0-56.62 (official)
> - [x] 5.4.0-56.60 (official)

I never care about versions I haven't installed that aren't latest in their Major.minor, really.

**Comment by bkw777** [comment]
not a bad idea

**Comment by bkw777** [comment]
the list is now sortable, so you can get one of those wishes by clicking on the Status header, which will group all the installed together
you can get a normal sort back by clicking on the Kernel header

**Comment by bkw777** [comment]
I think I'm not interested in filters for just the latest of each minor, or each installed minor. I'll probably never add that myself. I might accept a pr depending on how it was done.
