### ISSUE TITLE
linux-tools?

### ISSUE THREAD

**Issue by pigsflew** [bkw777/mainline#70]
Is it possible to get linux-tools installed for the mainline kernels?

**Comment by bkw777** [comment]
kernel.ubuntu.com/~kernel-ppa/mainline does not provide any packages called "linux-tools"

**Comment by pigsflew** [comment]
damn. Okay then this can be closed. Thanks!

**Comment by nyurik** [comment]
@bkw777 this seems like a common request, see also #79 by @Maziar123 . Do you know by any chance how we can ask the kernel-ppa maintainers to add tools to their site? Thanks!
