### ISSUE TITLE
Incomplete installs of several latest mainline kernels

### ISSUE THREAD

**Issue by StatusCode404** [bkw777/mainline#71]
Several of the latest mainline kernels don't have all files getting listed and as a result, I'm unable to install them.
e.g.:
5.9.13
5.9.11
5.9.9
5.9.5

I can for example install 5.9.12 but can't install 5.9.11 nor 5.9.13.

**Comment by gubagu** [comment]
Same here on Ubuntu 20.04.1 LTS.

**Comment by StatusCode404** [comment]
@bkw777 any ideas on the above?

**Comment by tosziro** [comment]
Looks like its broken build on Ubuntu side.
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.13/

Status is - Build failed

**Comment by nseb** [comment]
5.10.0-rc7 same problem

**Comment by niculw** [comment]
No files showing at all for 5.10.0 release

**Comment by bkw777** [comment]
> No files showing at all for 5.10.0 release

5.10.0 worked just fine for me just now.

Are we just seeing internet transientness? Anything that relies on getting something from the net will sometimes fail to be able to get something. It doesn't necessarily mean it's not there or doesn't work, it just means try again later. Maybe one second later, maybe 2 days later. Sometimes the network is fine but the files really don't exist, like broken builds. Sometimes the build was complete but the path from you to the server is temporarily bad, or the server is temporarily bad from load. Sometimes it's this app actually borking up it's cache or tmp files.

We definitely need to get some better form of error reporting so the user can tell the difference between some of those different cases above. If the build failed or the server isn't responding or the server isn't reachable, we should be able to tell that in each case and say so to the user.

**Comment by StatusCode404** [comment]
> > No files showing at all for 5.10.0 release
> 
> 5.10.0 worked just fine for me just now.
> 
> Are we just seeing internet transientness? Anything that relies on getting something from the net will sometimes fail to be able to get something. It doesn't necessarily mean it's not there or doesn't work, it just means try again later. Maybe one second later, maybe 2 days later. Sometimes the network is fine but the files really don't exist, like broken builds. Sometimes the build was complete but the path from you to the server is temporarily bad, or the server is temporarily bad from load. Sometimes it's this app actually borking up it's cache or tmp files.
> 
> We definitely need to get some better form of error reporting so the user can tell the difference between some of those different cases above. If the build failed or the server isn't responding or the server isn't reachable, we should be able to tell that in each case and say so to the user.

Hi Brian,
I believe what niculw is describing is what shows when you hover your mouse pointer over 5.10.0 release in the Mainline GUI.  Basically shows nothing.  But if you install anyway it picks up the correct files and installs them correctly.  
Then after install the GUI shows the right packages/files from there on.  If you uninstall it from that point, it will still continue to show the correct packages even if not installed.  it is just that first time where no packages are shown.

However that said I just tried now 5.9.13 and 5.9.14 and they both downloaded just one package and finished with no error when it should have shown a failure message.  
After refresh, both kernels where not installed and were both correctly showing not being in place in the GUI.  That adds to the confusion because it didn't fail during the install.

**Comment by niculw** [comment]
No i litterally mean the program says “amd64 directory doesnt exist” and then quits. No downloading of any files. Im gonna try to rebuild.

**Comment by niculw** [comment]
This is what happens if i use terminal to try and install 5.10.0:
![image](https://user-images.githubusercontent.com/19815838/102121090-b37d5b00-3e43-11eb-9ff6-28302e3283fd.png)

**Comment by brmmm3** [comment]
I've observed the same issue several times. Only the headers got downloaded and installed. A check at the repo showed that only the headers are available. To solve this issue please implement a check if all necessary files are available and only mark these kernel versions as installable.

**Comment by bkw777** [comment]
> please implement a check if all necessary files are available

There is no consistent rule to define "all necessary files"

So that's rather easier to demand than to accomplish.

We could maybe parse index.html for the "failed" notice, but that isn't consistent either.

It probably needs a table of different parsers or rules for different ranges of dates or kernel versions.

Maybe doable, but I have never been bothered by this enough to prioritize it.

**Comment by Matoran** [comment]
> > please implement a check if all necessary files are available
> 
> There is no consistent rule to define "all necessary files"
> 
> So that's rather easier to demand than to accomplish.
> 
> We could maybe parse index.html for the "failed" notice, but that isn't consistent either.
> 
> It probably needs a table of different parsers or rules for different ranges of dates or kernel versions.
> 
> Maybe doable, but I have never been bothered by this enough to prioritize it.

You can check the status file if it's 0 build is ok, otherwise isn't.

**Comment by bkw777** [comment]
fixed some time ago
