### ISSUE TITLE
A few build from source and install from deb issues

### ISSUE THREAD

**Issue by KnowZero** [bkw777/mainline#75]
Operating System: KDE Neon LTS (Ubuntu 20.04 Focal)

1. When installing the deb release, it gives an error saying dependencies not met for libjson-glib 1.5.2 , focal 20.04 which is the LTS ubuntu release has only up to libjson-glib 1.4.4

https://packages.ubuntu.com/search?keywords=libjson-glib&searchon=names

2. When trying to compile from source, it also gave me an error of xgettext not installed. Installing "gettext" fixed the issue but might want to add that to the install dependency for building.

**Comment by totof3110** [comment]
I have the same problem. :( I can "force install" the latest deb, which works fine functionally, but then apt reports broken dependencies and I have to uninstall it to resolve them.

**Comment by totof3110** [comment]
Workaround I found was to install the deb from the PPA: https://code.launchpad.net/~cappelikan/+archive/ubuntu/ppa/+packages.
