### ISSUE TITLE
Compilation error on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by smsm2014** [bkw777/mainline#76]
The following error appears when try to compile mainline with "make" in ubuntu 16.04 xenial.

> src/Utility/TeeJee.ProcessHelper.vala:149.28-149.39: error: The name `Signal' does not exist in the context of `Posix'
> 		Posix.kill (process_pid, Posix.Signal.TERM);
> 		                         ^^^^^^^^^^^^
> src/Utility/TeeJee.ProcessHelper.vala:155.27-155.38: error: The name `Signal' does not exist in the context of `Posix'
> 				Posix.kill (childPid, Posix.Signal.TERM);
> 				                      ^^^^^^^^^^^^
> Compilation failed: 2 error(s), 3 warning(s)
> 

I tried a fix by changing:
https://github.com/bkw777/mainline/blob/b9304da1cf30fe782a2869b33352540f88b4397f/src/Utility/TeeJee.ProcessHelper.vala#L149
to  Posix.SIGTERM

**Comment by bkw777** [comment]
Thanks for this.
added with c28d8919acab80421e2d12a028b0ceec75548650
