### ISSUE TITLE
No Internet by http proxy

### ISSUE THREAD

**Issue by istomyang** [bkw777/mainline#78]
https://github.com/bkw777/mainline/blob/b9304da1cf30fe782a2869b33352540f88b4397f/src/Gtk/MainWindow.vala#L320

I noticed the function code named `check_internet_connectivity` in `TeeJee.System.vala`. He use `ping` cmd to test internet connectivity. And I konw, ping use `ICMP`.
Suggestion: remove this codes or use curl command.

**Comment by bkw777** [comment]
Agreed. We don't care if ping works, we care if aria2c can download via https from kernel.ubuntu.com, so that's what it should test.
