### ISSUE TITLE
Latest kernel drivers may also require latest firmware

### ISSUE THREAD

**Issue by skoehler** [bkw777/mainline#85]
Having the latest kernel is nice, but where's the firmware package? Intel graphics drivers, Wifi drivers, etc. - they all require some firmware blob. Some kernel drivers may even require a recent version. Please add a possibility to install latest firmware from
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

**Comment by bkw777** [comment]
If you want that, then you don't want mainline kernel packages.
https://wiki.ubuntu.com/Kernel/MainlineBuilds
