### ISSUE TITLE
segmentation error 

### ISSUE THREAD

**Issue by Lolothepro** [bkw777/mainline#86]
https://www.youtube.com/watch?v=pR46uts0R6c
https://www.youtube.com/watch?v=znUJEnS3E2E

It launches but does not continue operations

**Comment by aleek** [comment]
Same here, vanilla 18.04.05.

And thank you for removing old versions of package from repository, now instead of just downgrading, I need to build from gound up.

Well played...

**Comment by bkw777** [comment]
1: Don't run mainline with sudo.
2: Please just cut & paste the --debug output instead of a youtube video.
3: There are a few old packages in the releases tab here on github. I do not provide or maintain the PPA.

**Comment by Lolothepro** [comment]
mainline 1.0.14
Distribution: Ubuntu 20.10
Architecture: amd64
Running kernel: 5.8.0-50-generic
D: query_thread() App.show_prev_majors: 0
D: query_thread() App.hide_unstable: true
D: file_parent(/home/rubuntu/.cache/mainline/index.html)
D: dir_create(/home/rubuntu/.cache/mainline)
D: File deleted: /home/rubuntu/.cache/mainline/index.html
D: dir_create(/tmp/.mainline_pxqMILCM)
D: Created directory: /tmp/.mainline_pxqMILCM
D: dir_create(/tmp/.mainline_xF2vufsa)
D: Created directory: /tmp/.mainline_xF2vufsa
D: build_script():
D: working_dir=/tmp/.mainline_xF2vufsa
D: file_write(/tmp/.mainline_xF2vufsa/download.list)
D: file_parent(/tmp/.mainline_xF2vufsa/download.list)
D: dir_create(/tmp/.mainline_xF2vufsa)
D: File saved:/tmp/.mainline_xF2vufsa/download.list
D: aria2c --no-netrc true -i '/tmp/.mainline_xF2vufsa/download.list' --show-console-readout=false --summary-interval=1 --auto-save-interval=1 --human-readable=false --enable-color=false --allow-overwrite --connect-timeout=15 --timeout=60 --max-concurrent-downloads=4 --max-file-not-found=3 --retry-wait=2
D: save_bash_script_temp(/tmp/.mainline_xF2vufsa/script.sh):/tmp/.mainline_xF2vufsa/script.sh
D: file_write(/tmp/.mainline_xF2vufsa/script.sh)
D: file_parent(/tmp/.mainline_xF2vufsa/script.sh)
D: dir_create(/tmp/.mainline_xF2vufsa)
D: File saved:/tmp/.mainline_xF2vufsa/script.sh
D: AsyncTask:begin():try
D: working_dir=/tmp/.mainline_xF2vufsa
Fetching index from kernel.ubuntu.com...
D: AsyncTask:finish(): before finish_task()
D: mv_partials_to_finals()
D: file_parent(/tmp/.mainline_pxqMILCM/index.html)
D: file_parent(/home/rubuntu/.cache/mainline/index.html)
D: dir_create(/home/rubuntu/.cache/mainline)
D: File moved: '/tmp/.mainline_pxqMILCM/index.html' → '/home/rubuntu/.cache/mainline/index.html'
D: dir_delete():Deleted: /tmp/.mainline_pxqMILCM
D: DownloadTask():finish_task():dir_delete(/tmp/.mainline_xF2vufsa):
D: dir_delete():Deleted: /tmp/.mainline_xF2vufsa
OK
D: highest_maj = 5
D: check_installed()
----------------------------------------------------------------------
D: query_installed_packages()
D: dir_create(/tmp/.mainline_y8vnGdZd)
D: Created directory: /tmp/.mainline_y8vnGdZd
D: file_write(/tmp/.mainline_y8vnGdZd/16199565002628326899)
D: file_parent(/tmp/.mainline_y8vnGdZd/16199565002628326899)
D: dir_create(/tmp/.mainline_y8vnGdZd)
D: File saved:/tmp/.mainline_y8vnGdZd/16199565002628326899
D: File deleted: /tmp/.mainline_y8vnGdZd/16199565002628326899
D: dir_delete():Deleted: /tmp/.mainline_y8vnGdZd
----------------------------------------------------------------------
----------------------------------------------------------------------
D: check_updates()
Erreur de segmentation

**Comment by bkw777** [comment]
This is possibly fixed with
https://github.com/bkw777/mainline/commit/d3b91b092bc470afcdadf8d316559c576dbfad45
Can you try it?

**Comment by Lolothepro** [comment]
It's good

**Comment by bkw777** [comment]
Thanks much
