### ISSUE TITLE
failed to exec error

### ISSUE THREAD

**Issue by lucserre** [bkw777/mainline#96]
Similar to the error you just solved rescently, could this be a similar issue?
PopOS, tmpfs mount of /tmp with noexec flag.
When clicking install on a kernel, I get:
E: Failed to execute child process “/tmp/.mainline_LIa7XI8v/16283626361933328036.sh”: Failed to execve: Permission denied

**Comment by bkw777** [comment]
Try it now.
Probably fixed by 008b61e2ca182123a188d36b62efefadac33fb1b

**Comment by lucserre** [comment]
yup, fixed.
Thanks!
